# Generated by Django 5.0.7 on 2024-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_passenger_remove_booking_no_of_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
