# Generated by Django 5.0.7 on 2024-07-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="age",
            field=models.CharField(max_length=20),
        ),
    ]
