# Generated by Django 5.0.7 on 2024-07-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_alter_passenger_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
    ]
