# Generated by Django 5.0.7 on 2024-07-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_remove_booking_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="train",
        ),
    ]
