# Generated by Django 5.0.7 on 2024-07-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0008_remove_booking_date_remove_booking_train"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="passengers",
        ),
    ]
