# Generated by Django 5.0.7 on 2024-07-29 07:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0009_remove_booking_passengers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.ManyToManyField(to="auth_app.passenger"),
        ),
        migrations.AddField(
            model_name="booking",
            name="train",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_app.train",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
